feature: ['enhancement/*', 'feature/*', 'feat/*']
documentation: ['docs/*', 'doc/*']
breaking-change: ['breaking/*', 'break/*']
bug: ['bug/*', 'fix/*', 'hotfix/*']
tests: ['test/*', 'tests/*']
dependency-update: ['dep/*', 'dependency/*', 'dependency-update/*']
scala-steward: ['update/*']
