# Don't edit this file!
# It is automatically updated after every release of https://github.com/invasi0m/.github
# If you want to suggest a change, please open a PR or issue in that repository

enhancement: [ 'enhancement/*', 'feature/*', 'feat/*' ]
documentation: [ 'docs/*', 'doc/*' ]
breaking-change: [ 'breaking/*', 'break/*' ]
bug: [ 'bug/*', 'fix/*', 'hotfix/*' ]
tests: [ 'test/*', 'tests/*' ]
dependency-update: [ 'dep/*', 'dependency/*', 'dependency-update/*' ]
scala-steward: [ 'update/*' ]
