name: "Update Pull Request"
on: pull_request

jobs:
  update_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: tzkhan/pr-update-action@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        base-branch-regex: '[a-z\d-_.\\/]+'
        head-branch-regex: '\d+'
        title-template: '[Issue %headbranch%] '
        body-template: |
          [Close %headbranch%](https://github.com/invasi0m/imputacion/issues/%headbranch%)
        body-update-action: 'suffix'
        body-uppercase-base-match: false
    
    - uses: tzkhan/pr-update-action@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        base-branch-regex: '[a-z\d-_.\\/]+'
        head-branch-regex: '(.*)endpoint(.*)'
        body-template: |
          Requirements:
            - [] Definition of algebra services
            - [] Integration of algebra services
            - [] Definition of route endpoints
            - [] Integration of route endpoints
            - [] Add IT test for route endpoints
        body-update-action: 'suffix'
        body-uppercase-base-match: false
